hapi:
  fhir:
    gateway:
      enabled: false
      multi-tenant: false
      targets:
    security:
      inbound:
        authentication:
          enabled: false
          proceed-to-authorization-on-failure: false
          proceed-to-authorization-on-no-auth: true
          user-realm-uri: http://localhost:9000/auth/realm/arogyam
        authorization:
          enabled: false
          allow-anonymous-access: true
          anonymous-access-permission:
            - name: fhir_read_all_of_type
              arguments:
                - Binary
                - Composition
            - name: fhir_transaction
            - name: fhir_capabilities
            - name: fhir_batch

project:
  arogyam:
    opensrp:
      whitelist:
        - method: get
          path: Questionnaire
          query-params:
            _id: "*"
        - method: get
          path: StructureMap
          query-params:
            _id: "*"
        - method: get
          path: List
          query-params:
            _id: "*"
        - method: get
          path: PlanDefinition
          query-params:
            _id: "*"
        - method: get
          path: Library
          query-params:
            _id: "*"
        - method: get
          path: Measure
          query-params:
            _id: "*"
        - method: get
          path: LocationHierarchy
          query-params:
            keycloak-uuid: "*"
        - method: get
          path: PractitionerDetails
          query-params:
            userId: "*"
        - method: get
          path: ActivityDefinition
          query-params:
            _id: "*"
        - method: get
          path: CodeSystem
          query-params:
            _id: "*"
        - method: get
          path: ConceptMap
          query-params:
            _id: "*"
        - method: get
          path: Device
          query-params:
            _id: "*"
        - method: get
          path: StructureDefinition
          query-params:
            _id: "*"
    task:
      labelling-plan-definition: OralCancerLabelImage
      screening-plan-definition: OralCancerPatientCare
      labelling-enabled: false
      screening-enabled: true